In [1]:
%matplotlib inline
import numpy as np;
from matplotlib import pyplot as plt

$\LaTeX \text{ commands here}
\newcommand{\R}{\mathbb{R}}
\newcommand{\im}{\text{im}\,}
\newcommand{\norm}[1]{||#1||}
\newcommand{\inner}[1]{\langle #1 \rangle}
\newcommand{\span}{\mathrm{span}}
\newcommand{\proj}{\mathrm{proj}}
$

<hr style="border: 5px solid black">

**Georgia Tech, CS 4540**

# L2:  Numpy & Linear Algebra

Jacob Abernethy

*Thursday, August 22, 2019*

### Outline

1. Review of Linear Algebra
    * Independence, span, and bases
    * Matrix Multiplication
    * Orthogonality & Projections
    * QR Factorization
2. Random Matrices

### Linear Algebra Resources

* **Videos:** 3blue1brown, [Essence of Linear Algebra](https://www.youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab) videos
* **Book:** Sheldon Axler, "*Linear Algebra Done Right*"


## Review:  Independence, Bases, Span

### Def:  Linear Combinations and Span

A **linear combination** of the vectors $x_1, \dots, x_n \in \R^m$ with coefficients $\alpha_1, \dots, \alpha_n \in \R$ is
    $$
    \alpha_1 x_1 + \cdots + \alpha_n x _n \in \R^m
    $$
The **span** of a set $S \subset \R^m$ of vectors is the subspace containing all (finite) linear combinations of elements from $S$,
    $$
    \mathrm{span}(S) = \left\{ \sum_{k=1}^n \alpha_k x_k \;\Bigg\vert\; x_k, \dots, x_n \in S, \alpha_k \in \R, n \in \mathbb{N} \right\} \subset \R^m
    $$

### Def:  Independence

Vectors $x_1, \dots, x_n \in \R^m$ are  **linearly dependent** if one of the vectors can be written as a (nontrivial) linear combination of the others, that is, there exist coefficients $\alpha_1, \dots, \alpha_n \in \R$ not all zero, such that
$$
\alpha_1 x_1 + \cdots + \alpha_n x_n = 0
$$
Otherwise, the vectors are **linearly independent**.

### Def:  Vector Space Basis

Independent vectors $x_1, \dots, x_n \in V$ form a **basis** for $V$ if their span is all of $V$,
$$
\mathrm{span}\{ x_1, \dots, x_n \} = V
$$

Here are some facts that you should prove for yourself:

* Every vector $x \in V$ has a unique expansion as a linear combination of basis vectors.
* Every basis for $V$ has the same number of elements.  This number is the **dimension**.
* If $\mathrm{dim}(V)=n$, then every set of $n+1$ vectors is linearly dependent.
* Every set of vectors $x_1,\dots,x_r \in V$ with $r < n$ can be extended to a basis $\mathcal{B} = \{ x_1, \dots, x_r, w_{r+1}, \dots, w_n \}$ for $V$.

## Review:  Matrix Multiplication

> **Key Idea:**  Think of matrix operations in terms of row- and column-vectors, rather than in terms of individual entries.

<div style="font-size: 10px; float: right">
This section borrows heavily from the first chapter of Trefethen & Bau, <a href="http://bookstore.siam.org/ot50/">"Numerical Linear Algebra"</a>.
</div>

### Matrix-Vector Multiplication (Row View)

Recall the following definition of matrix multiplication:

> If $x \in \mathbb{R}^n$ and $A \in \mathbb{R}^{m \times n}$, then the $i$th entry of $b = Ax \in \mathbb{R}^m$ is:

$$
b_i = \sum_{j=1}^n a_{ij} x_j \quad (i = 1,\dots,m)
$$

In other words, $b$ is a dot product between $x$ and the rows of $A$. If you think of $A$ as data matrix, it is useful to keep in mind the following interpretation:
<div style="margin: 20px; border: 1px solid black; padding: 20px; text-align:center">
Each <i>row</i> of $A$ is "scored" based on how well it aligns with the vector $x$.
</div>

### Matrix-Vector Multiplication (Column View)

An alternative interpretation that comes handy when you want to study the subspaces of matrix is:
<div style="margin: 20px; border: 1px solid black; padding: 20px; text-align:center">
If $b = Ax$, then $b$ is a linear combination of the <i>columns</i> of $A$, with coefficients from the vector $x$.
</div>

![Matrix-Vector Multiplication](images/matrix-vector-1.png)

### Problem 1:  Image and Kernel

Recall that the **range** or **image** of $A \in \R^{m \times n}$ is the set of vectors $y \in \R^m$ that can be written as $y = Ax$ for some $x \in \R^n$,

$$
\im A = \{ y \in \R^m \mid \exists x \in \R^n, y = Ax \}
$$

<div style="padding:20px;margin:20px;border: 1px solid black">
<b>Problem 1:</b>  Argue that $\im A$ is the space spanned by the columns of $A$.
</div>

> *Hint:*  Use the "column view" of matrix-vector multiplication!

### Solution 1:  Image and Kernel

<div style="padding:20px;margin:20px;border: 1px solid black">
<b>Problem 1:</b>  Argue that $\im A$ is the space spanned by the columns of $A$.
</div>

It helps to rewrite the image as $\im A = \{ Ax \mid x \in \R^n \}$.  Since $Ax$ is a linear combination of the columns $a_1, \dots, a_n \in \R^n$ of $A$ with coefficients from $x$, clearly $\im A = \mathrm{span}\{ a_1, \dots, a_n \}$.

### Matrix-Matrix Multiplication

<div style="margin: 20px; border: 1px solid black; padding: 20px; text-align:center">
If $B = AC$, then <em>each column of $B$ is a linear combination of the columns of $A$</em> with coefficients from the columns of $C$.
</div>

![Matrix-Matrix Multiplication](images/matrix-matrix-1.png)

## Let's try this in numpy!

In [26]:
A = np.random.randint(0,10,size=(2,3))
C = np.random.randint(0,10,size=(3,2))
B = A @ C
alsoB = np.zeros((2,2))
for i in range(2):
    alsoB[:,i] = A @ C[:,i]
print("A=",A)
print("C=",C)
print("B=",B)
print("alsoB=",alsoB)


A= [[4 4 2]
 [4 4 6]]
C= [[6 0]
 [7 4]
 [5 1]]
B= [[62 18]
 [82 22]]
alsoB= [[62. 18.]
 [82. 22.]]


In [7]:
A = np.random.randint(0,10,size=(2,3))
B = np.random.randint(0,10,size=(3,2))
C = A @ B
alsoC = np.zeros((2,2))
for i in range(2):
    alsoC[:,i] = A @ B[:,i]
print("A=",A)
print("B=",B)
print("C=",C)
print("alsoC=",alsoC)
# print((A,B,C,alsoC))

A= [[2 2 3]
 [8 5 3]]
B= [[4 2]
 [8 9]
 [7 5]]
C= [[45 37]
 [93 76]]
alsoC= [[45. 37.]
 [93. 76.]]


### Problem 2:  Multiplication by Triangular Matrix

<div style="margin: 20px; border: 1px solid black; padding: 20px; text-align:center">
<b>Problem 2:</b>  Consider $B = AR$, where $R$ an upper-triangular matrix with entires all equal to one on and above the diagonal.  Interpret the columns of $B$ using our new interpretation of matrix multiplication.
</div>

![Triangular matrix multiplication](images/matrix-triangular-1.png)

### Solution 2:  Multiplication by Triangular Matrix

<div style="margin: 20px; border: 1px solid black; padding: 20px; text-align:center">
<b>Problem 2:</b>  Consider $B = AR$, where $R$ an upper-triangular matrix with entires all equal to one on and above the diagonal.  Interpret the columns of $B$ using our new interpretation of matrix multiplication.
</div>

Since $B=AR$, the columns of $B$ are linear combinations of the columns of $A$, with coefficients taken from the columns of $R$.  Because of the diagonal structure of $R$, the $j$th column of $B$ is the sum of the first $j$ columns of $A$:

$$
b_j = A r_j = \sum_{k=1}^j a_j
$$

### Conclusion:  Matrix Multiplication

> If you hadn't seen these interpretations before, they may seem a little strange.  Keep at it!  Thinking about linear algebra in this way will help a lot in the long run.

## Review:  Norms and Inner Products

### Def:  Norm

A norm $\norm{\cdot} : V \rightarrow \R$ on a vector space $V$ satisfies
* $\norm{v} \geq 0$ for all $v \in V$ and $\norm{v} = 0 \iff v = 0$
* (Homogeneity) $\norm{ \alpha v } = | \alpha | \norm{v}$
* (Triangle Inequality) $\norm{v + w} \leq \norm{v} + \norm{w}$

Examples of norms include:
* $\norm{x}_2 = \sqrt{x_1^2 + \cdots + x_n^2} = \sqrt{x^T x}$
* $\norm{x}_1 = |x_1| + \cdots + |x_n|$
* $\norm{x}_\infty = \max_k |x_k|$

### Def:  Inner Product

A real-valued inner product $\inner{\cdot, \cdot} : V \times V \rightarrow \R$ satisfies

* (positive-definite) $\inner{x,x} \geq 0$ and $\inner{x,x} = 0 \iff x = 0$
* (symmetry) $\inner{x,y} = \inner{y,x}$
* (linearity) $\inner{\alpha x + y, z} = \alpha \inner{x,z} + \inner{y,z}$

The standard inner product on $\R^n$ is $\inner{x,y} = y^T x$.  Notice $\inner{x,x} = x^T x = \norm{x}_2^2$.

### Problem 3:  Orthogonal implies Independent

Recall that nonzero vectors $x, y \in \R^m$ are **orthogonal** if $\inner{x,y} = 0$.  A set of nonzero vectors is **orthogonal** if every pair is orthogonal.

<div style="padding:20px;margin:20px;border:1px solid black">
<b>Problem 3:</b> If $x_1, \dots, x_n \in \R^m$ are mutually orthogonal, then they are linearly independent.
</div>
    
> *Hint:* Try proof by contradiction.

### Solution 3:  Orthogonal Implies Independent

<div style="padding:20px;margin:20px;border:1px solid black">
<b>Problem 3:</b> If $x_1, \dots, x_n \in \R^m$ are non-zero mutually-orthogonal vectors, then they are linearly independent.
</div>

Suppose the vectors in $S$ are dependent, that is, some vector $x_k$ can be expressed as a linear combination of the others, $x_k = \sum_{j \neq k}^n \alpha_j x_j$ for some coefficients $\alpha_j \in \R$ not all zero.  Then,

$$
\inner{v_k, v_k} = \inner{v_k, \sum_{j \neq k} \alpha_j v_j} = \sum_{j \neq k} \alpha_k \inner{v_k, v_j} = 0
$$

But $v_k \neq 0$ so $\inner{v_k, v_k} = \norm{v_k} > 0$, a contradiction!

### Def:  Orthonormal Basis

An **orthonormal basis** is a set of vectors $q_1, \dots q_m \in \R^m$ such that
* $\{ q_1, \dots, q_m \}$ is a basis for $\R^m$
* Basis vectors are orthogonal, $\inner{q_i, q_j} = 0$ when $i \neq j$.
* Basis vectors have unit length, $\norm{q_j} = 1$ for all $j$

The coordinate expansion of $x \in \R^m$ is $x = \sum_{k=1}^m \inner{x, q_j} q_j$.

In other words, $\inner{x, q_j}$ is the *coefficient* on the basis vector $q_j$.

### Problem 4:  Orthogonal Projections

> Caution:  Not the same "orthogonal" as in "orthonormal basis"!

<div style="padding:20px; margin:20px; border: 1px solid black">
<b>Problem 4A:</b> Given a (unit) vector $q \in \R^m$, what is the transformation $Px = \mathrm{proj}_q(x)$ that projects $x$ onto $q$?  That is, onto $\span\{q\}$? *Note*: the transformation $P$ can be written as a <i>matrix</i>!

<b>Problem 4B:</b> Given orthonormal vectors $q_1, \dots, q_r \in \R^m$, what is the matrix transformation that projects $x$ onto $\span\{q_1, \dots, q_r\}$?

<b>(Challenge) Problem 4C:</b> Given linearly independent vectors $a_1, \dots, a_r \in \R^m$, what is the transformation projecting $x$ onto $\span\{ a_1, \dots, a_r \}$?
</div>

### Solution 4:  Orthogonal Projections

**Solution 4A**:  $P = qq^T$

**Solution 4B**:  $P = q_1 q_1^T + \cdots + q_r q_r^T = QQ^T$ where $Q$ has columns $q_1, \dots q_r$

**Solution 4C**:  $P = A(A^*A)^{-1} A^*$ where $A$ has columns $a_1, \dots, a_r$.

### Problem 5:  Complementary Projectors

<div style="padding:20px;margin:20px;border:1px solid black">
<b>Problem 5:</b>  What does the matrix $P = I - qq^T$ do?  Assume $\norm{q}_2=1$.
</div>



**Solution 5:** It projects onto the space orthogonal to $q$!

### Problem 6:  Orthogonal Matrices

A matrix $Q \in \R^{m \times m}$ is **orthogonal** (or unitary) if its columns $q_1, \dots, q_m \in \R^m$ are orthonormal.

<div style="padding:20px; margin:20px; border: 1px solid black">
<b>Problem 6A:</b> Prove that $Q^T = Q^{-1}$.  This is often used as the <em>definition</em> of an orthogonal matrix.

<b>Problem 6B:</b> Prove that orthogonal matrices preserve lengths, $\norm{Qx}_2 = \norm{x}_2$ for all $x \in \R^m$.

<b>Problem 6C:</b> Prove that $\det Q = \pm 1$.  (<em>Hint:</em> $\det A^T = \det A$ for any matrix)
</div>

### Solution 6:  Orthogonal Matrices

**Solution 6A:**  Suffices to show $Q^T Q = I$.  The $(i,j)$ entry is $\inner{q_i, q_j} = \delta_{ij}$ since the columns are orthonormal!

**Problem 6B:** $\norm{Qx}_2 = \sqrt{(Qx)^T (Qx)} = \sqrt{x^T Q^T Q x} = \sqrt{x^T x} = \norm{x}_2$

**Problem 6C:** Notice $1 = \det I = \det(Q^T Q) = \det(Q^T) \det(Q) = \det(Q)^2$, so $|\det(Q)|=1$.  Since $\det(Q) \in \R$, it is either $+1$ or $-1$.

## Let's make an orthonormal basis!

In [ ]:
n = 3
vecs = []
for i in range(n):
    veci = np.random.randn(n)
    # Now what?

In [21]:
n = 3
vecs = []
for i in range(n):
    veci = np.random.randn(n)
    for j in range(i):
        vecj = vecs[j]
        veci = veci - (veci @ vecj) * vecj
    veci = veci/np.sqrt(veci @ veci)
    vecs.append(veci)
    
Q = np.array(vecs)
np.round(Q @ Q.T,decimals=5)
Q @ Q.T

array([[ 1.00000000e+00,  6.74259405e-17, -5.42534456e-18],
       [ 6.74259405e-17,  1.00000000e+00, -6.16220564e-17],
       [-5.42534456e-18, -6.16220564e-17,  1.00000000e+00]])

In [15]:
for i in range(-1):
    print(i)